version: '3.7'

services:
  postgres:
    image: postgres:15.5
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: hotel_booking