name: Build and Push Docker Image to ECR

description: Build a Docker image and push it to AWS ECR

inputs:
  aws_region:
    description: 'AWS Region'
    required: true
  ecr_repository_name:
    description: 'ECR Repository Name'
    required: true
  image_tag:
    description: 'Docker Image Tag'
    default: 'latest'
  AWS_ACCESS_KEY_ID:
    required: true
  AWS_SECRET_ACCESS_KEY:
    required: true

runs:
  using: "docker"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ AWS_REGION }}

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ inputs.aws_region }} | docker login --username AWS --password-stdin ${{ AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}

    - name: Build Docker image
      run: |
        docker build -t ${{ inputs.ecr _repository_name }}:${{ inputs.image_tag }} .
        docker tag ${{ inputs.ecr_repository_name }}:${{ inputs.image_tag }} ${{ AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/${{ inputs.ecr_repository_name }}:${{ inputs.image_tag }}
      shell: bash

    - name: Push Docker image to ECR
      run: |
        docker push ${{ AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/${{ inputs.ecr_repository_name }}:${{ inputs.image_tag }}
      shell: bash
