name: Main Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Build project with Maven and run tests
        uses: ./.github/actions/build_maven

  build-and-push-to-ecr:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Build and Push Docker Image to ECR
        uses: ./.github/actions/build_image_and_push_to_ecr
        with:
          aws_region: $AWS_REGION
          ecr_repository_name: $ECR_REPOSITORY_NAME
          image_tag: 'latest'

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy Docker Image to EC2
        uses: ./.github/actions/deploy_docker_image_to_EC2
        with:
          aws_region: $AWS_REGION
          ecr_repository_name: $ECR_REPOSITORY_NAME
          image_tag: 'latest'
          ec2_user: 'ec2-user'
          ec2_host: '12.34.56.78'
          container_name: 'docker_container'