name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Generate dependency submission manifest
        run: mvn dependency:tree -DoutputType=dot -DoutputFile=target/dependency-submission.json

      - name: Submit dependencies to GitHub
        uses: github/dependency-submission-toolkit@v1
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          sha: ${{ github.sha }}
          manifest-file: target/dependency-submission.json